[package]
name = "birgitte_fibonacci"
version = "0.1.0"
edition = "2021"
description = "A library for calculating fibonacci"
license = "MIT" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = "0.3.3"
